"use client";
import {useState} from "react";

const eras=[
{year:"c. 3500 BCE",place:"Ancient Egypt",title:"The ritual begins",text:"Cosmetics become part of everyday life, ritual and burial culture. Eye pigments such as kohl are stored in purpose-made vessels and applied with small sticks.",tag:"ORIGINS"},
{year:"c. 1900 BCE",place:"Egypt",title:"Beauty gets a toolkit",text:"Archaeological finds preserve jars, ointments, mirrors, tweezers and applicators — evidence of a surprisingly sophisticated personal-care ritual.",tag:"TOOLS"},
{year:"1550–1300 BCE",place:"New Kingdom Egypt",title:"Kohl becomes iconic",text:"Black and green eye cosmetics are prepared from minerals including galena and malachite, then carried in decorated tubes.",tag:"KOHL"},
{year:"350–300 BCE",place:"Persia",title:"A beauty language travels",text:"Kohl appears in Persian contexts too, showing how cosmetic practices and their meanings moved across cultures.",tag:"CROSSROADS"},
{year:"Today",place:"Everywhere",title:"Adornment becomes an industry",text:"From pigments and powders to skincare and digital beauty culture, the ritual has changed enormously — but the human impulse to adorn remains.",tag:"NOW"}
];
const facts=[["No single inventor","Makeup evolved over thousands of years across different societies."],["Men wore it too","Ancient Egyptian evidence shows cosmetics were used by both men and women."],["Beauty had many jobs","Adornment could intersect with appearance, ritual, status and practical concerns."],["The container mattered","Cosmetic vessels could be elaborate objects in their own right — sometimes made from costly materials."]];

export default function Home(){
 const [active,setActive]=useState(0); const [open,setOpen]=useState<number|null>(null);
 return <main>
 <nav className="nav"><a className="brand" href="#top"><span className="brand-mark">✦</span> ART OF ADORNMENT</a><div className="nav-links"><a href="#story">Story</a><a href="#timeline">Timeline</a><a href="#materials">Materials</a><a href="#myths">Myths</a></div><span className="edition">VOL. 01 · BEAUTY</span></nav>
 <section id="top" className="hero"><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow">A VISUAL HISTORY OF COSMETICS</p><h1>Who <em>invented</em><br/>makeup?</h1><p className="hero-sub">There was no single inventor. The story begins thousands of years ago — with minerals, rituals, identity, and the ancient desire to adorn the human face.</p><a className="scroll" href="#story"><span>↓</span> Explore the story</a></div><div className="hero-art"><div className="sun"/><div className="face"><div className="eye e1"/><div className="eye e2"/><div className="nose"/><div className="mouth"/></div><div className="ring r1"/><div className="ring r2"/><span className="anno a1">KOHL<br/><small>c. 1550 BCE</small></span><span className="anno a2">PIGMENT<br/><small>MINERAL + OIL</small></span></div></section>
 <section id="story" className="intro"><div className="section-num">01 / THE QUESTION</div><div><p className="kicker">Forget the inventor myth.</p><h2>Makeup wasn't <i>invented.</i><br/>It <span>evolved.</span></h2><p className="lede">Long before lipstick counters and beauty tutorials, people were grinding minerals, mixing pigments and creating rituals around appearance. Ancient Egypt gives us some of the clearest surviving evidence — but it belongs to a much larger human story.</p><div className="source-note">Historical objects in The Metropolitan Museum of Art document Egyptian kohl containers, applicators and cosmetic sets dating back thousands of years. <a href="https://www.metmuseum.org/art/collection/search/560226" target="_blank">Explore the collection ↗</a></div></div></section>
 <section id="timeline" className="timeline"><div className="section-head"><div><p className="eyebrow">02 / THE LONG VIEW</p><h2>Five moments.<br/><i>One ancient ritual.</i></h2></div><p>Move through the timeline and see how the meaning and materials of adornment changed across time.</p></div><div className="timeline-layout"><div className="years">{eras.map((e,i)=><button key={e.year} className={active===i?"year active":"year"} onClick={()=>setActive(i)}><span>{e.year}</span><b>{e.place}</b></button>)}</div><article className="era-card"><div className="era-top"><span>{eras[active].tag}</span><span>{String(active+1).padStart(2,"0")} / 05</span></div><div className="era-body"><div className="era-number">{String(active+1).padStart(2,"0")}</div><div><p className="place">{eras[active].place}</p><h3>{eras[active].title}</h3><p>{eras[active].text}</p></div></div><div className="era-line"><span>◈</span><span>ADORNMENT · IDENTITY · RITUAL</span></div></article></div></section>
 <section id="materials" className="materials"><div className="material-title"><p className="eyebrow">03 / THE PALETTE</p><h2>What was<br/><i>makeup made of?</i></h2><p>Ancient cosmetics were closer to a small chemistry set than a modern makeup bag.</p></div><div className="material-grid"><div className="material big"><span className="material-symbol">●</span><strong>GALENA</strong><small>Dark mineral pigment</small><p>Ground into powder and used in black eye cosmetics known as kohl.</p></div><div className="material"><span className="material-symbol green">◆</span><strong>MALACHITE</strong><small>Green mineral pigment</small><p>Used for green eye paint.</p></div><div className="material"><span className="material-symbol red">●</span><strong>OCHRE</strong><small>Earth pigment</small><p>Natural mineral pigments produced warm reds and yellows.</p></div><div className="material"><span className="material-symbol gold">✦</span><strong>OILS + UNGUENTS</strong><small>Texture & fragrance</small><p>Oils and ointments were stored in dedicated vessels.</p></div></div></section>
 <section className="quote"><div className="quote-mark">“</div><blockquote>Beauty was never just about looking beautiful. It could be ritual, identity, status, protection — or simply pleasure.</blockquote><div className="quote-rule"/></section>
 <section id="myths" className="myths"><div className="section-head"><div><p className="eyebrow">04 / MYTHS & FACTS</p><h2>Let's clear<br/><i>the powder.</i></h2></div><p>Tap a card to reveal the historical context.</p></div><div className="fact-grid">{facts.map((f,i)=><button className={open===i?"fact open":"fact"} key={f[0]} onClick={()=>setOpen(open===i?null:i)}><span>0{i+1}</span><div><h3>{f[0]}</h3><p>{f[1]}</p></div><b>{open===i?"−":"+"}</b></button>)}</div></section>
 <footer><div><span className="brand-mark">✦</span><h2>ART OF<br/><i>ADORNMENT</i></h2></div><p>A small visual archive about a very old human ritual.<br/>Built from museum records and historical evidence.</p><div className="footer-links"><a href="https://www.metmuseum.org/art/collection/search/560226" target="_blank">The Met ↗</a><a href="https://www.britishmuseum.org/" target="_blank">British Museum ↗</a></div></footer>
 </main>
}