"use client";
import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import AdornmentField from "./components/AdornmentField";
import Adornment2DStory from "./components/Adornment2DStory";
gsap.registerPlugin(ScrollTrigger);

const objects=[
{image:"https://collectionapi.metmuseum.org/api/collection/v1/iiif/543990/1228612/main-image",title:"Kohl Jar",date:"ca. 1491–1473 BCE",material:"Serpentinite",detail:"A small container for something used around the eyes.",href:"https://www.metmuseum.org/art/collection/search/543990"},
{image:"https://collectionapi.metmuseum.org/api/collection/v1/iiif/547624/1228300/main-image",title:"Kohl Tube + Stick",date:"ca. 1550–1458 BCE",material:"Portable cosmetic",detail:"Container + applicator: an ancient beauty kit.",href:"https://www.metmuseum.org/art/collection/search/547624"},
{image:"https://collectionapi.metmuseum.org/api/collection/v1/iiif/554687/1203907/main-image",title:"Blue Kohl Tube",date:"ca. 1550–1300 BCE",material:"Faience + gold",detail:"A beautiful object for a practical ritual: storing cosmetic material.",href:"https://www.metmuseum.org/art/collection/search/554687"}];
const eras=[
["c. 1887–1813 BCE","MIDDLE KINGDOM","A tiny luxury","Kohl containers could be made from valuable materials."],
["c. 1550–1458 BCE","NEW KINGDOM","Beauty becomes portable","Tubes, sticks and grooming tools turn adornment into a kit."],
["c. 1491–1473 BCE","NEW KINGDOM","Galena leaves a trace","A cosmetic jar from the period preserves evidence of black eye cosmetic use."],
["c. 1300–1080 BCE","RAMESSIDE","Black + green","Galena and malachite appear in records of ancient Egyptian eye paint."]];
const materials=[["GALENA","BLACK","A dark mineral pigment.","#25221d"],["MALACHITE","GREEN","A green mineral pigment.","#65785e"],["OCHRE","EARTH","An earth pigment.","#9b6747"],["OILS","TEXTURE","A base for skin and scent.","#a47a3b"]];

export default function Home(){
const root=useRef<HTMLElement>(null);const[object,setObject]=useState(0);const[era,setEra]=useState(0);const[material,setMaterial]=useState<number|null>(null);const[quiz,setQuiz]=useState<string|null>(null);
useEffect(()=>{const ctx=gsap.context(()=>{
gsap.from(".hero-kicker",{y:25,opacity:0,duration:.8});gsap.from(".hero-title span",{y:"110%",opacity:0,duration:1,stagger:.1,delay:.15,ease:"power4.out"});gsap.from(".hero-answer",{y:25,opacity:0,duration:.8,delay:.55});gsap.from(".hero-art>*",{opacity:0,scale:.95,duration:1,stagger:.04,delay:.2});
gsap.to(".hero-face",{yPercent:-10,rotate:6,ease:"none",scrollTrigger:{trigger:".hero-cinema",start:"top top",end:"bottom top",scrub:1}});
gsap.to(".hero-orbit",{rotate:90,scale:1.12,ease:"none",scrollTrigger:{trigger:".hero-cinema",start:"top top",end:"bottom top",scrub:1.5}});
gsap.to(".hero-words",{yPercent:35,ease:"none",scrollTrigger:{trigger:".hero-cinema",start:"top top",end:"bottom top",scrub:1}});
gsap.utils.toArray<HTMLElement>(".reveal").forEach(el=>gsap.from(el,{y:55,opacity:0,duration:1,ease:"power3.out",scrollTrigger:{trigger:el,start:"top 82%",once:true}}));
const t=gsap.timeline({scrollTrigger:{trigger:".alchemy",start:"top top",end:"+=1800",scrub:1,pin:true}});
t.to(".alchemy-rock",{scale:1.5,rotate:180,x:-70,duration:1}).to(".alchemy-powder",{opacity:1,scale:1.35,duration:.7}).to(".alchemy-rock",{opacity:0,scale:.2,duration:.5},"<").to(".alchemy-pigment",{opacity:1,scale:1,duration:.8}).to(".alchemy-powder",{opacity:0,duration:.4}).to(".alchemy-eye",{opacity:1,scale:1.1,duration:.8}).to(".alchemy-pigment",{opacity:0,duration:.4}).to(".alchemy-headline",{opacity:1,y:0,duration:.8});
gsap.to(".marquee-track",{xPercent:-35,ease:"none",scrollTrigger:{trigger:".marquee",start:"top bottom",end:"bottom top",scrub:1}});
gsap.to(".final-orbit",{rotate:-120,scale:1.2,ease:"none",scrollTrigger:{trigger:".final-reveal",start:"top bottom",end:"bottom top",scrub:1}});
},root);return()=>ctx.revert()},[]);
return <main ref={root} id="top">
<nav className="nav"><a className="brand" href="#top"><span className="brand-mark">✦</span> ART OF ADORNMENT</a><div className="nav-links"><a href="#story">Story</a><a href="#evidence">Evidence</a><a href="#timeline">Time</a></div><span className="edition">CINEMATIC EDITION · 05</span></nav>
<section className="hero-cinema"><div className="hero-copy"><p className="eyebrow hero-kicker">A VISUAL HISTORY OF MAKEUP</p><h1 className="hero-title"><span>Who</span> <span><em>invented</em></span><br/><span>makeup?</span></h1><div className="hero-answer"><span>THE ANSWER IS WEIRDER THAN YOU THINK</span><strong>Nobody.</strong><p>No first lipstick. No first eyeliner genius. Just people experimenting with colour, texture, scent and ritual.</p></div><a className="scroll-cue" href="#story"><i>↓</i> Enter the rabbit hole</a></div><div className="hero-art"><AdornmentField/><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="hero-face"><div className="eye e1"/><div className="eye e2"/><div className="nose"/><div className="mouth"/></div><div className="hero-words"><span>KOHL</span><span>ROCK</span><span>RITUAL</span></div><div className="hero-note">FIG. 01<br/>ADORNMENT<br/><b>c. 1550 BCE → NOW</b></div><div className="hero-stamp">ARCHIVE<br/><b>OPEN</b></div></div><div className="hero-bottom">SCROLL TO UNLOCK THE STORY <span>↓</span></div></section>
<section id="story" className="manifesto"><div className="manifesto-number">01</div><div><p className="eyebrow">START HERE</p><h2>Makeup didn't<br/><i>begin in a bottle.</i></h2><p className="large-copy">It began with materials. A mineral. A plant. An earth pigment. Something someone wanted to put on the body.</p></div></section>
<section className="marquee" aria-hidden="true"><div className="marquee-track"><span>ROCK</span><b>→</b><span>POWDER</span><b>→</b><span>PIGMENT</span><b>→</b><span>KOHL</span><b>→</b><span>IDENTITY</span><b>→</b><span>ROCK</span></div></section>
<section className="alchemy"><AdornmentField/><div className="alchemy-copy"><p className="eyebrow">02 / THE CINEMATIC BIT</p><h2>From earth<br/><i>to eyeliner.</i></h2><p>Scroll slowly. Watch the material change.</p></div><div className="alchemy-stage"><div className="alchemy-rock">◆</div><div className="alchemy-powder">• • • • • • • • •</div><div className="alchemy-pigment">●</div><div className="alchemy-eye">—◉—</div><strong className="alchemy-headline">YOUR EYELINER<br/><i>STARTED AS A ROCK.</i></strong></div><div className="alchemy-steps"><span>01 FIND</span><span>02 GRIND</span><span>03 MIX</span><span>04 WEAR</span></div></section>
<section className="numbers"><div className="number-card reveal"><small>THE SCALE</small><strong>3,000+</strong><h3>YEARS</h3><p>Ancient cosmetic objects survive from periods thousands of years ago.</p></div><div className="number-card dark reveal"><small>THE MATERIAL</small><strong>GALENA</strong><h3>THE ROCK</h3><p>A mineral used as a dark pigment for eye cosmetics.</p></div><div className="number-card red reveal"><small>THE TWIST</small><strong>MEN</strong><h3>TOO.</h3><p>The history isn't a simple women-only story.</p></div></section>
<section className="illustration-2d"><div className="illustration-copy reveal"><p className="eyebrow">03 / CODED 2D</p><h2>Watch a tiny ritual<br/><i>come alive.</i></h2><p>No video. No stock footage. The scene is drawn and animated in code — mineral, bowl, brush, face.</p></div><Adornment2DStory/></section>
<section id="evidence" className="evidence-v5"><div className="section-head reveal"><div><p className="eyebrow">03 / SHOW ME THE RECEIPT</p><h2>Don't trust<br/><i>the illustration.</i></h2></div><p>Look at the thing itself. Objects are where the story becomes tangible.</p></div><div className="object-stage"><div className="object-visual"><img src={objects[object].image} alt={objects[object].title}/><span>0{object+1}</span><a href={objects[object].href} target="_blank" rel="noreferrer">VIEW MUSEUM RECORD ↗</a></div><div className="object-story"><p className="eyebrow">{objects[object].date}</p><h3>{objects[object].title}</h3><strong>{objects[object].material}</strong><p>{objects[object].detail}</p><div className="object-nav">{objects.map((o,i)=><button key={o.title} onClick={()=>setObject(i)} className={object===i?"active":""}><span>0{i+1}</span>{o.title}</button>)}</div></div></div></section>
<section id="timeline" className="timeline-v5"><div className="section-head reveal"><div><p className="eyebrow">04 / TIME, WITHOUT THE WALL OF TEXT</p><h2>Four moments.<br/><i>Thousands of years.</i></h2></div><p>Tap a moment. Get the detail that matters.</p></div><div className="time-line">{eras.map((e,i)=><button key={e[0]} onClick={()=>setEra(i)} className={era===i?"time-node active":"time-node"}><span className="node-dot"/><small>{e[0]}</small><b>{e[1]}</b></button>)}</div><article className="era-v5 reveal"><span>{eras[era][0]}</span><p>{eras[era][1]}</p><h3>{eras[era][2]}</h3><strong>{eras[era][3]}</strong><a href="https://www.metmuseum.org/art/collection/search/560226" target="_blank" rel="noreferrer">FOLLOW THE EVIDENCE ↗</a></article></section>
<section className="materials-v5"><div className="section-head reveal"><div><p className="eyebrow">05 / THE PALETTE</p><h2>Open the<br/><i>ancient bag.</i></h2></div><p>Four materials. Tap one and watch it take over the palette.</p></div><div className="material-orbit">{materials.map((m,i)=><button key={m[0]} className={material===i?"material-v5 active":"material-v5"} onClick={()=>setMaterial(material===i?null:i)} style={{"--material":m[3]} as React.CSSProperties}><span>{m[0]}</span><small>{m[1]}</small><i>{material===i?m[2]:"+"}</i></button>)}<div className="material-center">{material===null?"TAP A MATERIAL":materials[material][0]}</div></div></section>
<section className="quiz-v5"><div className="quiz-big"><p className="eyebrow">06 / ONE LAST QUESTION</p><h2>Why<br/><i>kohl?</i></h2></div><div className="quiz-card"><p>Ancient Egyptian eye cosmetics could be…</p>{["Just decoration","Part of beauty + ritual + daily life","Only for royalty"].map(x=><button key={x} onClick={()=>setQuiz(x)} className={quiz===x?"chosen":""}>{x}<span>→</span></button>)}{quiz&&<div className="answer"><b>{quiz==="Part of beauty + ritual + daily life"?"THE NUANCE IS THE POINT.":"NOT QUITE — HISTORY IS MESSIER."}</b><p>Cosmetics could overlap with beauty, ritual and everyday life. One object rarely tells the whole story.</p></div>}</div></section>
<section className="final-reveal"><AdornmentField/><div className="final-orbit"/><div className="final-content"><p className="eyebrow">THE ANSWER, FINALLY</p><h2>There wasn't<br/><i>one inventor.</i></h2><p>There were thousands of tiny experiments across people, places, materials and beliefs.</p><a href="#evidence">GO BACK TO THE OBJECTS ↑</a></div></section>
<footer><div><span className="brand-mark">✦</span><h2>ART OF<br/><i>ADORNMENT</i></h2></div><p>Curiosity first.<br/>Evidence always available.</p><div className="footer-links"><a href="https://www.metmuseum.org/" target="_blank" rel="noreferrer">The Met ↗</a><a href="https://www.britishmuseum.org/" target="_blank" rel="noreferrer">British Museum ↗</a></div></footer>
</main>}